export const useCases = [
  {
    id: "fullstack",
    category: "development",
    icon: "Code2",
    title: "全栈项目开发",
    subtitle: "从需求到部署，一气呀成",
    description: "描述你的需求，AI 负责搞建项目骨架、写核心逻辑、解决报错，直到部署上线。",
    efficiency: "节省 85% 时间",
    steps: ["描述项目需求和技术栈偏好", "AI 生成完整项目结构和代码", "审查代码，提出修改意见", "AI 自动部署到 Elastic Beanstalk", "获得可访问的公网 URL"],
    promptTemplate: "帮我构建一个全栈 Web 应用：\n\n项目名称：[项目名]\n核心功能：[功能描述]\n技术栈：Next.js + TypeScript + Tailwind CSS\n数据库：[PostgreSQL / MongoDB / SQLite]\n\n要求：\n- 包含用户认证\n- 响应式设计\n- 部署到 Elastic Beanstalk\n\n请先给我项目结构概览，确认后开始写代码。",
    tags: ["React", "Node.js", "部署", "TypeScript"],
  },
  {
    id: "github",
    category: "development",
    icon: "GitBranch",
    title: "GitHub 仓库管理",
    subtitle: "代码审查、Issue 处理、PR 流程",
    description: "连接 GitHub，直接在对话里管理仓库：查看文件、提交代码、处理 Issue、创建 PR。",
    efficiency: "节省 70% 时间",
    steps: ["连接 GitHub MCP 集成", "告诉 AI 仓库地址和任务", "AI 读取代码并分析", "AI 直接提交修改或创建 PR", "在 GitHub 上审核合并"],
    promptTemplate: "查看我的仓库 [用户名/仓库名]，帮我：\n\n1. 阅读 README 和主要源文件\n2. 找出代码中的潜在问题\n3. 列出 3 个改进建议\n4. 直接在仓库里修复最简单的一个问题并提交 PR\n\n仓库地址：https://github.com/[用户名/仓库名]",
    tags: ["Git", "Code Review", "PR", "Issue"],
  },
  {
    id: "research",
    category: "research",
    icon: "Search",
    title: "深度研究报告",
    subtitle: "多轮搜索，交叉验证，结构化输出",
    description: "对任意主题进行深度调研，自动搜索多个来源，交叉验证信息，生成带引用的专业报告。",
    efficiency: "节省 90% 时间",
    steps: ["提供研究主题和关注角度", "AI 规划搜索策略", "多轮迭代搜索和信息整合", "交叉验证关键数据", "输出结构化 Markdown 报告"],
    promptTemplate: "请对以下主题进行深度研究：\n\n主题：[研究主题]\n关注角度：[技术趋势 / 市场分析 / 竞pinyin对比 / 最佳实践]\n输出要求：\n- 3000字以上\n- 包含数据和引用来源\n- 分章节组织\n- 最后给出结论和建议\n\n请先告诉我研究计划，确认后开始执行。",
    tags: ["调研", "报告", "数据分析", "竞pinyin品"],
  },
  {
    id: "ppt",
    category: "content",
    icon: "Presentation",
    title: "PPT 自动生成",
    subtitle: "大厂简约风格，直接下载",
    description: "输入主题和要求，AI 自动生成内容完整、视觉精美的 PowerPoint 演示文稿。",
    efficiency: "节省 80% 时间",
    steps: ["描述主题、受众、风格偏好", "AI 规划幻灯片大纲", "确认大纲后开始生成", "AI 输出 .pptx 文件", "下载，按需微调"],
    promptTemplate: "帮我生成一份 PPT：\n\n主题：[主题名称]\n幻灯片数量：10-12 张\n目标受众：[内部汇报 / 客户展示 / 公开演讲]\n风格：简约大厂风（深色背景 + 蓝色强调色）\n内容重点：[核心要点1, 要点2, 要点3]\n\n请先给我大纲，确认后开始生成 PPTX 文件。",
    tags: ["演示", "PPTX", "设计", "汇报"],
  },
  {
    id: "file",
    category: "content",
    icon: "FileText",
    title: "文件处理与转换",
    subtitle: "PDF、Word、Excel 全覆盖",
    description: "上传文件，AI 提取内容、分析数据、生成新文档，支持 PDF/Word/Excel/CSV 等格式。",
    efficiency: "节省 75% 时间",
    steps: ["上传文件到对话", "说明处理目标", "AI 解析文件内容", "执行提取/转换/分析", "输出新文件或结构化数据"],
    promptTemplate: "请处理我上传的文件：\n\n文件类型：[PDF / Word / Excel / CSV]\n任务：\n- [ ] 提取关键信息，生成摘要\n- [ ] 转换为 [目标格式]\n- [ ] 分析数据并生成图表\n- [ ] 按模板重新排版\n\n[上传文件后描述具体需求]",
    tags: ["PDF", "Word", "Excel", "数据提取"],
  },
  {
    id: "image",
    category: "content",
    icon: "Image",
    title: "AI 图片生成",
    subtitle: "文字描述变视觉内容",
    description: "用 Gemini 图像模型生成原创图片，支持各种风格：写实、插画、赛博朋克、极简设计。",
    efficiency: "节省 95% 时间",
    steps: ["描述想要的画面内容", "指定风格、色调、构图", "AI 生成 1-4 张候选图", "选择满意的图片", "下载或继续调整"],
    promptTemplate: "帮我生成一张图片：\n\n画面内容：[描述主体和场景]\n风格：[赛博朋克 / 极简插画 / 写实摄影 / 水彩]\n色调：[冷色调 / 暖色调 / 黑白 / 霹虹]\n构图：[特写 / 全景 / 俰视 / 侧面]\n用途：[封面图 / 社交媒体 / 演示配图 / 壁纸]\n\n生成 2 张候选，供我选择。",
    tags: ["Gemini", "图片", "设计", "创意"],
  },
  {
    id: "data",
    category: "research",
    icon: "BarChart3",
    title: "数据分析与可视化",
    subtitle: "从原始数据到洞察图表",
    description: "上传数据集，AI 完成清洗、统计分析，生成 Python 图表或 Excel 报表，输出业务洞察。",
    efficiency: "节省 88% 时间",
    steps: ["上传 CSV/Excel 数据文件", "描述分析目标", "AI 清洗数据并探索", "生成统计图表", "输出分析报告"],
    promptTemplate: "帮我分析这份数据：\n\n数据文件：[上传 CSV/Excel]\n分析目标：\n1. 数据基本情况（行数、字段、缺失值）\n2. [核心指标] 的趋势分析\n3. [维度A] vs [维度B] 的相关性\n4. 找出异常点和关键洞察\n\n输出：Python 可视化图表 + 文字洞察摘要",
    tags: ["数据", "Python", "图表", "Excel"],
  },
  {
    id: "automation",
    category: "development",
    icon: "Zap",
    title: "工作流自动化",
    subtitle: "把重复劳动变成一行指令",
    description: "描述你的重复性工作流，AI 编写自动化脚本：批量文件处理、API 集成、定时任务等。",
    efficiency: "节省 92% 时间",
    steps: ["描述当前手动流程", "AI 分析自动化可能性", "编写并测试脚本", "处理边界情况", "交付可直接使用的脚本"],
    promptTemplate: "帮我自动化这个工作流：\n\n当前流程：[描述手动步骤，越详细越好]\n触发条件：[每天定时 / 文件变化时 / 手动触发]\n输入：[数据来源]\n期望输出：[结果格式]\n技术要求：[Python / Shell / Node.js]\n\n请先确认理解，然后写脚本并做测试。",
    tags: ["脚本", "自动化", "Python", "API"],
  },
];

export const skills = [
  { name: "deep-research", desc: "深度网络调研，多轮搜索交叉验证", category: "研究" },
  { name: "pptx", desc: "生成和编辑 PowerPoint 演示文稿", category: "内容" },
  { name: "pdf", desc: "PDF 读取、合并、提取、OCR", category: "内容" },
  { name: "docx", desc: "Word 文档创建、编辑和格式化", category: "内容" },
  { name: "xlsx", desc: "Excel 表格处理、公式、图表", category: "内容" },
  { name: "nano-banana-2", desc: "Gemini 图片生成与编辑", category: "创意" },
  { name: "canvas-design", desc: "海报、视觉设计 PNG/PDF 输出", category: "创意" },
  { name: "eb-deploy", desc: "一键部署到 AWS Elastic Beanstalk", category: "开发" },
  { name: "claude-api", desc: "调用 Claude API 构建 AI 应用", category: "开发" },
  { name: "web-search", desc: "实时搜索互联网和抓取网页", category: "研究" },
  { name: "s3-file", desc: "文件上传下载，生成分享链接", category: "工具" },
  { name: "context7", desc: "获取任意库/框架的最新文档", category: "开发" },
];

export const learningPath = [
  {
    day: "Day 1",
    phase: "建立感觉",
    tasks: [
      { id: "t1", text: "发送第一条消息，试试普通对话" },
      { id: "t2", text: "上传一个文件，让 AI 读取并总结" },
      { id: "t3", text: "让 AI 生成一张图片" },
    ],
  },
  {
    day: "Day 2-3",
    phase: "掌握核心工具",
    tasks: [
      { id: "t4", text: "用 deep-research 调研一个行业话题" },
      { id: "t5", text: "生成一份 PPT，下载并检查质量" },
      { id: "t6", text: "连接 GitHub，读取你的一个仓库" },
    ],
  },
  {
    day: "Day 4-5",
    phase: "构建第一个项目",
    tasks: [
      { id: "t7", text: "描述一个简单 Web 项目需求" },
      { id: "t8", text: "让 AI 完整构建并部署，获得 URL" },
      { id: "t9", text: "把源码推送到 GitHub 保存" },
    ],
  },
  {
    day: "Day 6-7",
    phase: "建立高效工作流",
    tasks: [
      { id: "t10", text: "识别你日常 3 个重复性任务" },
      { id: "t11", text: "让 AI 为其中 1 个写自动化脚本" },
      { id: "t12", text: "设置定时提醒，形成使用习惯" },
    ],
  },
];

export const tips = [
  { title: "上下文越多，结果越好", content: "告诉 AI 你是谁、目标是什么、已经做了什么。一段背景描述比来回追问省 5 倍时间。" },
  { title: "先要大纲，再要内容", content: "复杂任务先让 AI 给方案，确认后再执行。避免花大时间生成你不需要的东西。" },
  { title: "用文件代替粘贴", content: "上传原始文件比复制粘贴内容更可靠。AI 能直接读取 PDF/Excel/代码文件，不会丢格式。" },
  { title: "明确输出格式", content: "说清楚你要什么格式：Markdown / JSON / PPTX / Python 脚本。模糊的要求会得到模糊的输出。" },
  { title: "连续对话保持上下文", content: "在同一个对话里迭代，AI 记得之前说的所有内容。新开对话等于重新开始。" },
  { title: "出错时给错误信息", content: "如果结果不对，把错误日志或截图完整发给 AI。\"不行\"这两个字是最没用的反馈。" },
];

export const faq = [
  { q: "Kollab 和普通 ChatGPT 有什么区别？", a: "Kollab 集成了 GitHub、Notion 等外部服务，有专业技能（pptx、deep-research 等），能直接部署项目、操作文件，不只是对话。" },
  { q: "生成的文件在哪里下载？", a: "AI 会自动上传到 S3 并给你下载链接，链接有效期 24 小时。如果没看到链接，说一句「上传并给我下载链接」即可。" },
  { q: "一次对话可以做多复杂的项目？", a: "相当复杂。一次对话可以完成：需求分析 → 代码开发 → 本地测试 → 部署上线 → 推送 GitHub，全流程不用离开对话框。" },
  { q: "如何连接我的 GitHub？", a: "在 Kollab 工作区安装 GitHub MCP 集成，授权后 AI 就能直接读写你的仓库，不需要手动复制粘贴代码。" },
  { q: "图片生成用的是什么模型？", a: "nano-banana-2 技能调用 Google Gemini 图像模型，生成质量高，支持文生图和图片编辑。" },
  { q: "部署的网站会一直在线吗？", a: "Elastic Beanstalk 部署的环境临时有效，约 24 小时。AI 会同时提供源码 ZIP 下载，你可以随时重新部署到自己的服务器。" },
];
