#!/usr/bin/env node
/**
 * generate-blog.mjs
 * 
 * Reads all Markdown files from content/blog/*.md and generates
 * lib/blog-data.ts — a plain TypeScript data file with no fs/path imports.
 * 
 * Run automatically via "prebuild" script in package.json.
 */

import fs   from "fs";
import path from "path";
import { fileURLToPath } from "url";
import matter from "gray-matter";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT      = path.join(__dirname, "..");
const BLOG_DIR  = path.join(ROOT, "content/blog");
const OUT_FILE  = path.join(ROOT, "lib/blog-data.ts");

const files = fs
  .readdirSync(BLOG_DIR)
  .filter((f) => f.endsWith(".md"))
  .sort();

const posts = files.map((filename) => {
  const raw = fs.readFileSync(path.join(BLOG_DIR, filename), "utf-8");
  const { data, content } = matter(raw);
  return {
    slug:     data.slug     ?? filename.replace(/\.md$/, ""),
    title:    data.title    ?? "",
    date:     data.date     ?? "",
    summary:  data.summary  ?? "",
    tags:     Array.isArray(data.tags) ? data.tags : [],
    author:   data.author   ?? "",
    readTime: typeof data.readTime === "number" ? data.readTime : 5,
    content:  content.trimStart(),
  };
});

// Sort newest-first
posts.sort((a, b) => (a.date < b.date ? 1 : a.date > b.date ? -1 : 0));

// Build output
const lines = [
  "// AUTO-GENERATED by scripts/generate-blog.mjs",
  "// Source of truth: content/blog/*.md — edit those files, not this one.",
  "// Regenerated automatically before every build.",
  "",
  'import type { BlogPost } from "./blog";',
  "",
  "export const blogPostsData: BlogPost[] = [",
];

for (const post of posts) {
  lines.push("  {");
  lines.push(`    slug:     ${JSON.stringify(post.slug)},`);
  lines.push(`    title:    ${JSON.stringify(post.title)},`);
  lines.push(`    date:     ${JSON.stringify(post.date)},`);
  lines.push(`    summary:  ${JSON.stringify(post.summary)},`);
  lines.push(`    tags:     ${JSON.stringify(post.tags)},`);
  lines.push(`    author:   ${JSON.stringify(post.author)},`);
  lines.push(`    readTime: ${post.readTime},`);
  lines.push(`    content:  ${JSON.stringify(post.content)},`);
  lines.push("  },");
}

lines.push("];");
lines.push("");

const output = lines.join("\n");
fs.writeFileSync(OUT_FILE, output, "utf-8");

console.log(`✓ Generated ${posts.length} posts → lib/blog-data.ts`);
for (const p of posts) {
  console.log(`  · ${p.date}  ${p.slug}`);
}
